### PR TITLE
Cache plugins when the service worker is ready

### PR DESCRIPTION
**Pull request by oeway**

### CODE REVIEW

**Comment by oeway** [comment]
@MartinHjelmare Do you know why `npm run lint` is not working here?

**Comment by MartinHjelmare** [comment]
Do you mean locally?

**Comment by oeway** [comment]
> Do you mean locally?

Yes, for some reason, the eslinter is not configured correctly, I tried to add options but never work.

**Comment by MartinHjelmare** [comment]
It'll take some time to go through the eslint docs etc. I might have some time later in the week.

**Pull request merged**
